config/routes.rb
Rails.application.routes.draw do
  
  resources :markers
  resources :categories
  resources :types
  get 'data-categories' , to: 'categories#data_categories'
  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  ##belongs_to :category,optional: true
  belongs_to :type , foreign_key: "type_id", dependent: :destroy
  has_many :markers , dependent: :destroy
  has_many :subcategories, class_name: "Category", foreign_key: "category_id", dependent: :destroy
  def name_type
    Type.references(:category).where(id: type_id).pluck :name
  end
  def name_parent(id)
    
    if id
      Category.find_by(id: id).name
    else
      ""
    end

  end

  def self.build_data
    categories = Category.where(category_id: nil)
    build(categories)
  end

  def self.build(all)
    st = all.map{|t| info ={
      "id" => t.id,
      "name"=> t.name,
      "subcategory_id" => t.subcategory_name,
      "type_id" => t.one_type,
      "makers"=>t.many_markers,
      "public" => t.public
    
    }}
  end
def self.type_name(id)
Type.find_by(id: id).name
end
  def subcategory_name
    all = Category.references(:subcategory).where(category_id: id)

    all.map{|v| info={
      "id" => v.id,
      "name" => v.name,
      "subcategory_id" =>v.subcategory_name,
      "markers" => v.many_markers
    }}
  end

  def many_markers
    Marker.references(:category).where(category_id: id)
  end

  def one_type
    Type.references(:category).where(id: type_id)
  end

  
end

app/models/marker.rb
class Marker < ApplicationRecord
  belongs_to :category

  def name_category
    Category.references(:marker).where(id: category_id).pluck :name
  end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :categories, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  
  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @category = Category.new
    @categories_ids = Category.all.map{ |category| [category.name, category.id]}
    @types = Type.all.map{ |type| [type.name, type.id]}
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
   
  end

  # GET /categories/1/edit
  def edit
    @categories_ids = Category.all.map{ |category| [category.name, category.id]}
    @types = Type.all.map{ |type| [type.name, type.id]}
  end

  # category /categories or /categories.json
  def create
    @category = Category.new(category_params)

   unless @category.save
    render json: @category.errors, status: :unprocessable_entity
   end
    
  end
  def data_categories
    @categories = Category.build_data
    render json: @categories
  end
  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category.update(category_params)
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :public, :category_id, :type_id)
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        
        hash = Category.group(:type_id).count
       ## keys = hash.keys.map(&:name)
       ## [keys, hash.values].transpose.to_h
      
       arr =[]
       ha = {}
       keys = hash.each{| key, value| arr <<{ name: Category.type_name(key), id: key, value: value} }
       arr.each do |ele|
         ha[ele[:name]]= ele[:value]
       end
       
        @categories = ha
      
    end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]
  
  # GET /markers or /markers.json
  def index
    @markers = Marker.all
    @marker = Marker.new
    @categories = Category.all.map{ |category| [category.name, category.id]}
  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    @categories = Category.all.map{ |category| [category.name, category.id]}
  end

  # GET /markers/1/edit
  def edit
    @categories = Category.all.map{ |category| [category.name, category.id]}
  end

  # marker /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)

   unless @marker.save
    render json: @marker.errors, status: :unprocessable_entity
   end
    
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    @marker.update(marker_params)
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:name,:url,:category_id)
    end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]
  
  def index
    @types = Type.all
    @type = Type.new
  end

  def show
  end

  # GET /posts/new
  def new
    @type = Type.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @type = Type.new(type_params)

   unless @type.save
    render json: @type.errors, status: :unprocessable_entity
   end
    
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @type.update(type_params)
  end

  def destroy
    @type.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit( :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/categories/_category.html.erb
<li id="<%= category.id%>">
    <p><strong><%= category.name_type[0] %></strong>
      <%if category.name_parent(category.category_id).empty?%> 
           > <%= category.name %>
        <% else %>
        > <%= category.name_parent(category.category_id) %> >
        <%= category.name %>
    <% end %>
        </p>
        <p>
        <%= link_to 'Show', category,remote: true , class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_category_path(category), remote: true,class: "btn btn-success" %>
        <%= link_to 'Destroy', category,remote: true, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
        </>
</li>

app/views/categories/_form.html.erb
<%= form_for @category, remote: true, data: { confirm: '¿desea continuar para crear este category?' } do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :public %>
    <%= form.select :public,[false,true] %>
  </div>
    <div class="field">
    <%= form.label :category_id %>
    <%= form.select(:category_id, options_for_select(@categories_ids)) %>
  </div>
     <div class="field">
    <%= form.label :type_id %>
    <%= form.select(:type_id, options_for_select(@types)) %>
  </div>
  <div class="actions">
    <%= form.submit data: {disable_with: "Creando"}%>
  </div>
<% end %>

app/views/categories/create.js.erb
$("#all-categories").append(`<%= escape_javascript render @category%>`)

app/views/categories/destroy.js.erb
$(`#<%=@category.id%>`).remove()

app/views/categories/edit.js.erb
$(`#<%=@category.id%>`).html(`<%= j render 'form', category: @category %>`)

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
<%= render 'form', category: @category %>

<ul id="all-categorires">
  <%= render @categories%>
</ul>

<br>

app/views/categories/show.js.erb
alert(`<%= @category.name%>`)

app/views/categories/update.js.erb
$(`#<%=@category.id%>`).html(`<%= j render @category %>`)

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<div>
    <h2>All Categories</h2>
    <%= pie_chart @categories%>
    <%# <%= column_chart  @sales_group_by_month, legend: "top",title: "Last 12 months",prefix: "$",thousands: "." %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Bookmarks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= categories_path %>">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= types_path %>">Types</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= markers_path %>">Markers</a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
    <%= yield %>

    <%= javascript_pack_tag(params[:controller]) %>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_for @marker, remote: true, data: { confirm: '¿desea continuar para crear este marker?' } do |form| %>
  <% if marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>
    <div class="field">
    <%= form.label :category_id %>
    <%= form.select(:category_id, options_for_select(@categories)) %>
  </div>

  <div class="actions">
    <%= form.submit data: {disable_with: "Creando"}%>
  </div>
<% end %>

app/views/markers/_marker.html.erb
<li id="<%= marker.id%>">
        <strong><%= marker.name %></strong>
        <p><a href=<%= marker.url %> target="_blank"><%= marker.url %></a></p>
        <p><%= marker.name_category[0] %></p>
        <p>
        <%= link_to 'Show', marker,remote: true , class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_marker_path(marker), remote: true,class: "btn btn-success" %>
        <%= link_to 'Destroy', marker,remote: true, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
        </>
</li>

app/views/markers/create.js.erb
$("#all-markers").append(`<%= escape_javascript render @marker%>`)

app/views/markers/destroy.js.erb
$(`#<%=@marker.id%>`).remove()

app/views/markers/edit.js.erb
$(`#<%=@marker.id%>`).html(`<%= j render 'form', marker: @marker %>`)

app/views/markers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Markers</h1>
<%= render 'form', marker: @marker %>

<ul id="all-markers">
  <%= render @markers%>
</ul>

<br>

app/views/markers/show.js.erb
alert(`<%= @marker.name%>`)

app/views/markers/update.js.erb
$(`#<%=@marker.id%>`).html(`<%= j render @marker %>`)

app/views/types/_form.html.erb
<%= form_for @type, remote: true, data: { confirm: '¿desea continuar para crear este Type?' } do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit data: {disable_with: "Creando"}%>
  </div>
<% end %>

app/views/types/_type.html.erb
<li id="<%= type.id%>">
        <strong><%= type.name %></strong>
        <p>
        <%= link_to 'Show', type,remote: true , class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_type_path(type), remote: true,class: "btn btn-success" %>
        <%= link_to 'Destroy', type,remote: true, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
        </>
</li>

app/views/types/create.js.erb
$("#all-types").append(`<%= escape_javascript render @type%>`)

app/views/types/destroy.js.erb
$(`#<%=@type.id%>`).remove()

app/views/types/edit.js.erb
$(`#<%=@type.id%>`).html(`<%= j render 'form', type: @type %>`)

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>
<%= render 'form', type: @type %>

<ul id="all-types">
  <%= render @types%>
</ul>

<br>

app/views/types/show.js.erb
alert(`<%= @type.name%>`)

app/views/types/update.js.erb
$(`#<%=@type.id%>`).html(`<%= j render @type %>`)